#!/bin/bash
(set -o igncr) 2>/dev/null && set -o igncr; # comment is needed

LOG_DATE_STAMP=`eval date '+%Y%m%d..%H:%M:%S'`
echo "---------- $LOG_DATE_STAMP ----------" 

# git pull for BackEnd
cd /cygdrive/c/gjs/git_stuff/portal/BackEnd
git pull


# backend maven build
cd /cygdrive/c/gjs/git_stuff/portal/BackEnd
mvn clean install -Dmaven.test.skip=true


# frontend maven build
cd /cygdrive/c/gjs/git_stuff/portal/FrontEnd
mvn clean package -Dmaven.test.skip=true

exit 0
