#!/bin/bash
(set -o igncr) 2>/dev/null && set -o igncr; # comment is needed

LOG_DATE_STAMP=`eval date '+%Y%m%d..%H:%M:%S'`
echo "---------- $LOG_DATE_STAMP ----------" 

for ((i=1; i<=1000; i++))

do

      output=$(( $i % 2))

      if [ $output -ne 0 ]

      then
      echo "We got odd numbers: $i"
      fi
done

exit 0
