#!/bin/bash
(set -o igncr) 2>/dev/null && set -o igncr; # comment is needed

# a cmd-line memory file

COMMON_FILE=common.env

check_for_common_file()
{
   # -r is true if file exists and is readable
   if [ ! -r $1 ] ; then
      echo "$1 NoT found"
      echo " it should exist and contain entries like: "
      echo "   home=/home/gsimpson  {on unix} "
      echo "   home=c:\bin          {on windows} "
      echo "   rememberfile=$home/<some-dir>/reminders/.remember"
      exit 0
   fi
}

set_common_env()
{
   while read record
   do
      echo $record | awk -F'=' '{print $1}'
      echo $record | awk -F'=' '{print $2}'

      #echo $record | awk -F'=' '{print $1}'|sed 's/\"//g'
      #echo $record | awk -F'=' '{print $2}'|sed 's/\"//g'
      #eval `echo $record | awk -F'=' '{print $1}'|sed 's/\"//g''='echo $record | awk -F'=' '{print $2}'`

   done < $COMMON_FILE

   #echo $home
   #echo $rememberfile
}

display_parameters()
{
   echo "--------------------"
   echo "dollar @ = $@"
   echo "dollar # = $#"
   echo "dollar 1 = $1"
   echo "dollar 2 = $2"
   echo "dollar 3 = $3"
   echo "dollar 4 = $4"
   echo "home=$home"
   echo "rememberfile=$rememberfile"
}

#
# MAIN script routine
#
#check_for_common_file $COMMON_FILE

#save original script parameters
ORIG_PARAMS=$@

#set common attributes
#COMMON_SETINGS=`set_common_env $@`
#set -- `echo $COMMON_SETTINGS`
#display_parameters $@
#echo $1
#echo $2
#eval `echo $1=$2`
#eval `echo $3=$4`

#reset the ORIG_PARAMS
set -- `echo $ORIG_PARAMS`

#display_parameters $@



#most of the above stuff did not translate well to my machine
#  the following (short) code section is the important stuff
#GJS_REMEMBERFILE=c:/bin/reminders/.remember
##GJS_REMEMBERFILE=~/bin/reminders/.remember
GJS_REMEMBERFILE=/cygdrive/c/gjs/bin/reminders/.remember

# $# is the number of parameters
if [ $# == 0 ] ; then
      echo "Enter note, end with ^D: "
      #cat - >> $rememberfile
      cat - >> $GJS_REMEMBERFILE
   else
      #echo "$@" >> $rememberfile
      echo "$@" >> $GJS_REMEMBERFILE
   fi

LOG_DATE_STAMP=`eval date '+%Y%m%d..%H:%M:%S'`
#echo "---------- $LOG_DATE_STAMP ----------" >> $rememberfile
echo "---------- $LOG_DATE_STAMP ----------" >> $GJS_REMEMBERFILE

exit 0

