#!/bin/bash


pushd /home/gsimpson/gjs/git_stuff/project-fischer/_docker

#-- shutdown docker images
docker-compose stop
docker-compose rm -f
docker image prune -a -f
docker network prune -f
docker system prune -a -f
#-- rm all docker images
docker image rm $(docker image ls -a -q)

popd


