#!/bin/bash

echo -s " run localRP-server instead"

##cd ~/gjs/git_stuff/RealPlay/realplay_server
#
#  From :/home/gsimpson/gjs/git_stuff/RealPlay/realplay_server/README.md
#
#You can start the server by running:
#
##sh run_server_localhost.sh
#Or alternatively:
#
# Run with logging out to stderr. Also logs to REALPLAY_LOG_PATH if set. May need to alter port (5000) if running AA
# The dashes after logfie can be replaced with a file if you want to log to files you can watch.
#gunicorn --bind=0.0.0.0:5000 --workers=2 -t 60 --reload --log-level=debug --capture-output --enable-stdio-inheritance application --access-logfile - --log-file -

